### ISSUE TITLE
How to add to ESPHome?

### ISSUE THREAD

**Issue by FutureProofHomes** [gnumpi/esphome_matrixio#17]
Slighly confused.  I have everything up and running, and connect to Home Assistant working with a voice pipeline.  How do I add the Matrix Voice to ESPHome.  My goal is to get OTA updates working.  TY!

**Comment by gnumpi** [comment]
If you have OTA enabled in your configuration, you only need the raspberry pi for flash your ESP32 the first time. Afterwards you can upload a new firmware from any computer within your network running ESPHome, and hence, you can use the Matrix Voice as standalone satellite without raspberry pi. 

You are enabling OTA with the ota component in your configuration:
```yaml
ota:

```
For uploading a new firmware you can use:
```bash
esphome compile your_config.yaml
esphome upload your_config.yaml
```

What do you mean by adding the Matrix Voice to ESPHome? In HA you should find the matrix voice at "settings->devices & services->ESPHome'. Or do you mean to let it appear in the ESPHome dashboard in HA? 
I never used the dashboard, but adding the matrix voice the conventional way by the provided "new device" button should only be possible if you are running HA on the same raspi as the matrixio voice is connected to. But I never tried it. But after flashing the matrix voice the first time manually, it should also be possible to copy your esphome configuration, which you have already created and running, somewhere into the HA configuration folder, but I have no idea where. You could ask in some esphome forum maybe?
